// apps/api/src/components/user/UserSidebar.tsx
"use client"

import AsyncContainer from '@/components/layout/AsyncContainer'
import Login from '@/components/Login'
import { useCurrentUser } from '@/context/CurrentUserProvider'

import { useLayout } from '@/context/LayoutProvider'
import type { ThemeName } from '@peeps/ui'
import { themeNames, themes } from '@peeps/ui'
import { Check, Computer, Egg, Leaf, LucideProps, Moon, Sun, User } from 'lucide-react'
import { ForwardRefExoticComponent, RefAttributes, useSyncExternalStore } from 'react'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuPortal, DropdownMenuSeparator, DropdownMenuSub, DropdownMenuSubContent, DropdownMenuSubTrigger, DropdownMenuTrigger } from '../ui/dropdown-menu'

type UserSidebarProps = Record<string, never>

const emptySubscribe = () => () => {}
const useMounted = () => useSyncExternalStore(emptySubscribe, () => true, () => false)

type ModeTypes = {
  value: 'system' | 'light' | 'dark'
  label: string,
  icon : ForwardRefExoticComponent<Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>>
}

  const themeModes: ModeTypes[] = [
    { value: 'system', label: 'System', icon: Computer },
    { value: 'light', label: 'Light', icon: Sun },
    { value: 'dark', label: 'Dark', icon: Moon },
  ]
  
function ThemeIcon(props: { icon: string }) {
  switch (props.icon) {
    case 'egg':
      return <Egg className="h-4 w-4" />
    case 'leaf':
      return <Leaf className="h-4 w-4" />
    default:
      return <Sun className="h-4 w-4" />
  }
}

const UserSidebar = (_props: UserSidebarProps) => {
  const { auth, user, userLoading } = useCurrentUser()
  const { setTheme, theme, colorTheme, mode, setMode, navigate } = useLayout()
  const mounted = useMounted()
  const currentTheme = colorTheme as ThemeName


  return (
    <AsyncContainer isLoading={[userLoading]}>
      {!user ? (
        <Login buttonText="Log in" className="w-full" />
      ) : (
        <div className="rounded-lg border border-border">
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <button type="button" className='flex items-center gap-2 p-2'>
                <div className="hidden text-left md:block bg-primary rounded-full p-1">
                  <User className="h-10 w-10 text-secondary-foreground" />
                </div>
                <div className='flex-grow text-left'>
                  <p>{user.preferredName}</p>
                  <p className="text-xs text-muted">{user.fullName}</p>
                </div>
              </button>
            </DropdownMenuTrigger>
            <DropdownMenuPortal>
              <DropdownMenuContent
                className="z-50 min-w-[12rem] overflow-hidden rounded-md border border-border bg-popover p-1 text-popover-foreground shadow-md"
              >
                <DropdownMenuItem
                  className="cursor-pointer select-none rounded-sm px-2 py-1.5 text-sm outline-none focus:bg-accent focus:text-accent-foreground"
                  onSelect={() => {
                    navigate('/notifications')
                  }}
                >
                  Notifications
                </DropdownMenuItem>

                <DropdownMenuItem
                  className="cursor-pointer select-none rounded-sm px-2 py-1.5 text-sm outline-none focus:bg-accent focus:text-accent-foreground"
                  onSelect={() => {
                    navigate('/profile')
                  }}
                >
                  Profile
                </DropdownMenuItem>

                <DropdownMenuItem
                  className="cursor-pointer select-none rounded-sm px-2 py-1.5 text-sm outline-none focus:bg-accent focus:text-accent-foreground"
                  onSelect={() => {
                    navigate('/settings')
                  }}
                >
                  Settings
                </DropdownMenuItem>

                <DropdownMenuSeparator className="my-1 h-px bg-border" />

                <DropdownMenuSub>
                  <DropdownMenuSubTrigger className="flex w-full cursor-pointer select-none items-center justify-between rounded-sm px-2 py-1.5 text-sm outline-none focus:bg-accent focus:text-accent-foreground">
                    <span>Theme</span>
                  </DropdownMenuSubTrigger>
                  <DropdownMenuPortal>
                    <DropdownMenuSubContent
                      sideOffset={8}
                      className="z-50 min-w-[12rem] overflow-hidden rounded-md border border-border bg-popover p-1 text-popover-foreground shadow-md"
                    >
                      {themeModes.map((m) => (
                        <DropdownMenuItem
                          key={m.value}
                          className="flex cursor-pointer select-none items-center justify-between gap-2 rounded-sm px-2 py-1.5 text-sm outline-none focus:bg-accent focus:text-accent-foreground"
                          disabled={!mounted}
                          onSelect={() => setMode(m.value)}
                        >
                          <span className="flex items-center gap-2">
                            <m.icon className="h-4 w-4" />
                            {m.label}
                          </span>
                          {mounted && mode === m.value && <Check className="h-4 w-4" />}
                        </DropdownMenuItem>
                      ))}
                      <DropdownMenuSeparator className="my-1 h-px bg-border" />
                      {themeNames.map((name) => {
                        const meta = themes[name]
                        const isActive = mounted && currentTheme === name
                        return (
                          <DropdownMenuItem
                            key={name}
                            className="flex cursor-pointer select-none items-center justify-between gap-2 rounded-sm px-2 py-1.5 text-sm outline-none focus:bg-accent focus:text-accent-foreground"
                            disabled={!mounted}
                            onSelect={() => setTheme(name)}
                          >
                            <span className="flex items-center gap-2">
                              <ThemeIcon icon={meta.icon} />
                              {meta.name}
                            </span>
                            {isActive && <Check className="h-4 w-4" />}
                          </DropdownMenuItem>
                        )
                      })}
                    </DropdownMenuSubContent>
                  </DropdownMenuPortal>
                </DropdownMenuSub>

                <DropdownMenuItem
                  className="cursor-pointer select-none rounded-sm px-2 py-1.5 text-sm outline-none focus:bg-accent focus:text-accent-foreground"
                  onSelect={async () => {
                    await auth.signOut()
                  }}
                >
                  Log out
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenuPortal>
          </DropdownMenu>
        </div>
      )}
    </AsyncContainer>
  )
}

UserSidebar.displayName = "UserSidebar"
export default UserSidebar

// apps/web/components/UserSidebar.vue
<script setup lang="ts">
import { Button } from '@/components/ui/button'
import { Separator } from '@/components/ui/separator'
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from '@/components/ui/sheet'
import { useCurrentUser } from '@/composables/useCurrentUser'
import { useLayout } from '@/composables/useLayout'
import { themeNames, themes, type ThemeName } from '@peeps/ui'
import { Bell, Check, Computer, Egg, Leaf, LogOut, Moon, Settings, Sun, User } from 'lucide-vue-next'
import LoginDialog from './LoginDialog.vue'

type ModeType = {
  value: 'system' | 'light' | 'dark'
  label: string
  icon: typeof Sun
}

const themeModes: ModeType[] = [
  { value: 'system', label: 'System', icon: Computer },
  { value: 'light', label: 'Light', icon: Sun },
  { value: 'dark', label: 'Dark', icon: Moon },
]

const { user, userLoading, auth } = useCurrentUser()
const { setTheme, setMode, theme, colorTheme, mode, navigate } = useLayout()

const currentTheme = computed(() => colorTheme.value as ThemeName)

const themeIcons: Record<string, typeof Sun> = {
  egg: Egg,
  leaf: Leaf,
}

function getThemeIcon(iconName: string) {
  return themeIcons[iconName] || Sun
}

const sheetOpen = ref(false)

function handleNavigation(path: string) {
  navigate(path)
  sheetOpen.value = false
}
</script>

<template>
  <div class="p-4">
    <!-- Not logged in: Login button -->
    <div v-if="!user && !userLoading" class="flex items-center gap-3">
      <!-- <LoginDialog button-text="Login" button-class="w-full" /> -->
       <BoxDialog />
    </div>

    <!-- Loading -->
    <div v-else-if="userLoading" class="flex items-center gap-3">
      <div class="h-10 w-10 rounded-full bg-muted animate-pulse" />
      <div class="hidden md:block space-y-1">
        <div class="h-4 w-20 bg-muted rounded animate-pulse" />
      </div>
    </div>

    <!-- Logged in: User menu -->
    <Sheet v-else v-model:open="sheetOpen">
      <SheetTrigger as-child>
        <button
          type="button"
          class="flex items-center gap-2 p-2 w-full rounded-lg hover:bg-accent transition-colors"
        >
          <div class="h-10 w-10 rounded-full bg-primary flex items-center justify-center">
            <User class="h-5 w-5 text-primary-foreground" />
          </div>
          <div class="hidden md:block text-left flex-1">
            <p class="text-sm font-medium">{{ user?.preferredName || user?.name || 'User' }}</p>
            <p v-if="user?.fullName" class="text-xs text-muted-foreground">{{ user.fullName }}</p>
          </div>
        </button>
      </SheetTrigger>

      <SheetContent side="left" class="w-[280px] p-0">
        <SheetHeader class="p-4">
          <SheetTitle>Account</SheetTitle>
        </SheetHeader>

        <div class="px-2 py-2 space-y-1">
          <button
            class="w-full flex items-center gap-2 px-3 py-2 rounded-sm text-sm hover:bg-accent hover:text-accent-foreground transition-colors text-left"
            @click="handleNavigation('/notifications')"
          >
            <Bell class="h-4 w-4" />
            Notifications
          </button>

          <button
            class="w-full flex items-center gap-2 px-3 py-2 rounded-sm text-sm hover:bg-accent hover:text-accent-foreground transition-colors text-left"
            @click="handleNavigation('/profile')"
          >
            <User class="h-4 w-4" />
            Profile
          </button>

          <button
            class="w-full flex items-center gap-2 px-3 py-2 rounded-sm text-sm hover:bg-accent hover:text-accent-foreground transition-colors text-left"
            @click="handleNavigation('/settings')"
          >
            <Settings class="h-4 w-4" />
            Settings
          </button>

          <Separator class="my-2" />

          <!-- Theme Section -->
          <div class="px-3 py-1 text-xs font-medium text-muted-foreground">Theme</div>

          <!-- Mode Selection -->
          <button
            v-for="m in themeModes"
            :key="m.value"
            class="w-full flex items-center justify-between px-3 py-2 rounded-sm text-sm hover:bg-accent hover:text-accent-foreground transition-colors"
            @click="setMode(m.value)"
          >
            <span class="flex items-center gap-2">
              <component :is="m.icon" class="h-4 w-4" />
              {{ m.label }}
            </span>
            <Check v-if="mode === m.value" class="h-4 w-4" />
          </button>

          <Separator class="my-2" />

          <!-- Theme Selection -->
          <button
            v-for="name in themeNames"
            :key="name"
            class="w-full flex items-center justify-between px-3 py-2 rounded-sm text-sm hover:bg-accent hover:text-accent-foreground transition-colors"
            @click="setTheme(name)"
          >
            <span class="flex items-center gap-2">
              <component :is="getThemeIcon(themes[name].icon)" class="h-4 w-4" />
              {{ themes[name].name }}
            </span>
            <Check v-if="currentTheme === name" class="h-4 w-4" />
          </button>

          <Separator class="my-2" />

          <button
            class="w-full flex items-center gap-2 px-3 py-2 rounded-sm text-sm hover:bg-accent hover:text-accent-foreground transition-colors text-left"
            @click="auth.signOut()"
          >
            <LogOut class="h-4 w-4" />
            Log out
          </button>
        </div>
      </SheetContent>
    </Sheet>
  </div>
</template>
